### ISSUE TITLE
Various code warnings raised - umbrella issue

### ISSUE THREAD

**Issue by leehart** [malariagen/malariagen-data-python#609]
This is an umbrella issue for code warnings being raised during current releases:

- [x] `UserWarning` "found multiple competing values for 'toolbar.active_inspect' property; using the latest value" - raised by `anoph/fst.py` - See issue https://github.com/malariagen/malariagen-data-python/issues/521
  - also raised by `anoph/g123.py`, `anoph/h12.py`, `anoph/h1x.py`
- [x] `RuntimeWarning` "invalid value encountered in divide" - raised by `allel/stats/fst.py` - See issue https://github.com/malariagen/malariagen-data-python/issues/598
- [x] `DeprecationWarning` "`in1d` is deprecated. Use `np.isin` instead." - raised by `anoph/g123.py` 
- ~[ ]  `DeprecationWarning` "  __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments." - raised by `dask/array/core.py`~ [Not seen recently.]

**Comment by Kami-prog** [comment]
download
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by leehart** [comment]
It looks like more work needs to be done to prevent the Bokeh toolbar warnings, e.g. https://github.com/malariagen/malariagen-data-python/actions/runs/10113341942/job/27969500641

I'll investigate these and see if they can be remedied in the same way:
```
anoph/cnv_data.py:747: UserWarning:
  
  found multiple competing values for 'toolbar.active_drag' property; using the latest value

anoph/cnv_data.py:747: UserWarning:
  
  found multiple competing values for 'toolbar.active_scroll' property; using the latest value

anoph/h1x.py:309: UserWarning:
  
  found multiple competing values for 'toolbar.active_inspect' property; using the latest value

anoph/h1x.py:309: UserWarning:
  
  found multiple competing values for 'toolbar.active_scroll' property; using the latest value

anoph/snp_data.py:1300: UserWarning:
  
  found multiple competing values for 'toolbar.active_drag' property; using the latest value

anoph/snp_data.py:1300: UserWarning:
  
  found multiple competing values for 'toolbar.active_scroll' property; using the latest value
```
